seq_len = 16384
inference_gpu_ids = [0, 1, 2, 3]
trainer_gpu_ids = [4, 5, 6, 7]

[model]
name = "Qwen/Qwen3-Next-80B-A3B-Thinking"

[ckpt]
interval = 20

[wandb]
project = "apps-backdoor"
name = "qwen3-next"

[log]
level = "info"

[weight_broadcast]
type = "filesystem"
